apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: todo
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: microservice-todo/api
        imagePullPolicy: Never
        ports:
        - name: api-service
          containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 3000
    targetPort: api-service
