apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-deployment
  namespace: todo
  labels:
    app: repository
spec:
  selector:
    matchLabels:
      app: repository
  replicas: 1
  template:
    metadata:
      labels:
        app: repository
    spec:
      containers:
      - name: repository
        image: microservice-todo/repository
        imagePullPolicy: Never
        ports:
        - name: repo-service
          containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: repo-service
spec:
  selector:
    app: repository
  ports:
  - port: 3000
    targetPort: repo-service
