apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: todo
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 1
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: microservice-todo/todo
        imagePullPolicy: Never
        ports:
        - name: todo-service
          containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: todo-service
spec:
  selector:
    app: todo
  ports:
  - port: 3000
    targetPort: todo-service
